apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: wtc-list-fix-exists-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: wtc-list-fix-exists-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /watch_list/fixed_income/exists
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /watch_list/fixed_income/exists
